name: Sync to Cloudflare R2
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Configure rclone
      run: |
        rclone config create cloudflare_r2 s3 \
          env_auth=true \
          endpoint=${{ secrets.R2_ENDPOINT_URL }} \
          access_key_id=${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }} \
          secret_access_key=${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }} \
          region=auto

    - name: Sync files to Cloudflare R2
      run: |
        rclone sync . cloudflare_r2:${{ secrets.R2_BUCKET_NAME }} --s3-storage-class=STANDARD  --exclude ".git/*" --exclude ".github/*"
